export const data = {
  _id: "6452be892819185db5d84bf6",
  name: "Party",
  restaurants: [
    {
      id: "MJEwQTtY9mzWJLCU7e25bw",
      alias: "draft-republic-san-marcos-san-marcos-2",
      name: "Draft Republic - San Marcos",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/I04V2yKBIZa43hdeGa9DYg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/draft-republic-san-marcos-san-marcos-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 310,
      categories: [
        { alias: "beergardens", title: "Beer Gardens" },
        { alias: "tradamerican", title: "American (Traditional)" },
        { alias: "gastropubs", title: "Gastropubs" },
      ],
      rating: 4.5,
      coordinates: { latitude: 33.1359, longitude: -117.15821 },
      transactions: [],
      price: "$$",
      location: {
        address1: "255 Redel Rd",
        address2: null,
        address3: null,
        city: "San Marcos",
        zip_code: "92078",
        country: "US",
        state: "CA",
        display_address: ["255 Redel Rd", "San Marcos, CA 92078"],
      },
      phone: "+17602903520",
      display_phone: "(760) 290-3520",
      distance: 1850.3058136270963,
    },
    {
      id: "PczpdcaqLR9EaGUcbqkS2w",
      alias: "buona-forchetta-san-marcos-san-marcos-2",
      name: "Buona Forchetta - San Marcos",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/XwaE_HMPYxHsOC7L1WSLCQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/buona-forchetta-san-marcos-san-marcos-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 256,
      categories: [
        { alias: "pizza", title: "Pizza" },
        { alias: "italian", title: "Italian" },
      ],
      rating: 4,
      coordinates: { latitude: 33.13546739553502, longitude: -117.1593791 },
      transactions: [],
      price: "$$",
      location: {
        address1: "250 N City Dr",
        address2: "",
        address3: null,
        city: "San Marcos",
        zip_code: "92078",
        country: "US",
        state: "CA",
        display_address: ["250 N City Dr", "San Marcos, CA 92078"],
      },
      phone: "+14425153147",
      display_phone: "(442) 515-3147",
      distance: 1785.886278792327,
    },
    {
      id: "3rqvZnEUbGIuCKHsBWLFLg",
      alias: "amalfi-cucina-italiana-san-marcos-2",
      name: "Amalfi Cucina Italiana",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/Zwx1mgr9gEc_oIpFG2EfpQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/amalfi-cucina-italiana-san-marcos-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 620,
      categories: [
        { alias: "italian", title: "Italian" },
        { alias: "pizza", title: "Pizza" },
        { alias: "bars", title: "Bars" },
      ],
      rating: 4,
      coordinates: {
        latitude: 33.12392496202204,
        longitude: -117.20782744781258,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "1035 La Bonita Dr",
        address2: null,
        address3: null,
        city: "San Marcos",
        zip_code: "92078",
        country: "US",
        state: "CA",
        display_address: ["1035 La Bonita Dr", "San Marcos, CA 92078"],
      },
      phone: "+17606533230",
      display_phone: "(760) 653-3230",
      distance: 3241.313608912303,
    },
    {
      id: "SCrEOKR5uKHXo0a4BUsPhA",
      alias: "aria-restaurant-san-marcos",
      name: "Aria Restaurant",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/NOhBFyOZjxs78VybGoonkQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/aria-restaurant-san-marcos?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 137,
      categories: [
        { alias: "persian", title: "Persian/Iranian" },
        { alias: "mediterranean", title: "Mediterranean" },
      ],
      rating: 4.5,
      coordinates: { latitude: 33.14891, longitude: -117.19797 },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "1650 Descanso Ave",
        address2: null,
        address3: "",
        city: "San Marcos",
        zip_code: "92078",
        country: "US",
        state: "CA",
        display_address: ["1650 Descanso Ave", "San Marcos, CA 92078"],
      },
      phone: "+17605397890",
      display_phone: "(760) 539-7890",
      distance: 2157.625933928102,
    },
    {
      id: "okfpAclrSbJCXt3854GOQA",
      alias: "up-in-smoke-bbq-san-marcos-3",
      name: "Up In Smoke BBQ",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/ghJEXGWVO9pCpPioLjbcLQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/up-in-smoke-bbq-san-marcos-3?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 555,
      categories: [
        { alias: "bbq", title: "Barbeque" },
        { alias: "newamerican", title: "American (New)" },
        { alias: "beerbar", title: "Beer Bar" },
      ],
      rating: 4,
      coordinates: { latitude: 33.13501, longitude: -117.18554 },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "925 W San Marcos Blvd",
        address2: null,
        address3: "",
        city: "San Marcos",
        zip_code: "92078",
        country: "US",
        state: "CA",
        display_address: ["925 W San Marcos Blvd", "San Marcos, CA 92078"],
      },
      phone: "+17602903532",
      display_phone: "(760) 290-3532",
      distance: 826.0909997066193,
    },
  ],
  votes: {
    MJEwQTtY9mzWJLCU7e25bw: 0,
    PczpdcaqLR9EaGUcbqkS2w: 0,
    "3rqvZnEUbGIuCKHsBWLFLg": 0,
    SCrEOKR5uKHXo0a4BUsPhA: 0,
    okfpAclrSbJCXt3854GOQA: 0,
  },
  createdAt: "2023-05-03T20:05:29.551Z",
  updatedAt: "2023-05-03T20:44:50.734Z",
  __v: 0,
};
