export const data = {
  businesses: [
    {
      id: "FZTcyTxoUqPh-cth8d_IEw",
      alias: "noa-by-september-in-bangkok-new-haven",
      name: "NOA by September in Bangkok",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/4MUjAVAWfenmy996JcZeIg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/noa-by-september-in-bangkok-new-haven?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 74,
      categories: [
        {
          alias: "thai",
          title: "Thai",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 41.3052233,
        longitude: -72.928234,
      },
      transactions: ["pickup", "delivery"],
      location: {
        address1: "200 Crown St",
        address2: null,
        address3: "",
        city: "New Haven",
        zip_code: "06510",
        country: "US",
        state: "CT",
        display_address: ["200 Crown St", "New Haven, CT 06510"],
      },
      phone: "+14752386290",
      display_phone: "(475) 238-6290",
      distance: 688.5860074939492,
    },
    {
      id: "9W9XpUTRcCrNXwRlCvYhlg",
      alias: "the-luke-brasserie-new-haven",
      name: "the LUKE BRASSERIE",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/0hPjbdhU87lMT6dmCI40_w/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/the-luke-brasserie-new-haven?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 46,
      categories: [
        {
          alias: "brasseries",
          title: "Brasseries",
        },
        {
          alias: "cafes",
          title: "Cafes",
        },
        {
          alias: "bars",
          title: "Bars",
        },
      ],
      rating: 5,
      coordinates: {
        latitude: 41.3068623,
        longitude: -72.9287533,
      },
      transactions: [],
      location: {
        address1: "261 College St",
        address2: null,
        address3: "",
        city: "New Haven",
        zip_code: "06510",
        country: "US",
        state: "CT",
        display_address: ["261 College St", "New Haven, CT 06510"],
      },
      phone: "+14756668001",
      display_phone: "(475) 666-8001",
      distance: 546.3455129815136,
    },
    {
      id: "hj3lUGoxpIWVxXX9Qmr55A",
      alias: "zeneli-pizzeria-and-cucina-napoletana-new-haven-2",
      name: "Zeneli Pizzeria & Cucina Napoletana",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/NILw-5dAheokdSrMm1YxXA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/zeneli-pizzeria-and-cucina-napoletana-new-haven-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 411,
      categories: [
        {
          alias: "pizza",
          title: "Pizza",
        },
        {
          alias: "italian",
          title: "Italian",
        },
        {
          alias: "wine_bars",
          title: "Wine Bars",
        },
      ],
      rating: 5,
      coordinates: {
        latitude: 41.30261,
        longitude: -72.9163,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "138 Wooster St",
        address2: "",
        address3: null,
        city: "New Haven",
        zip_code: "06511",
        country: "US",
        state: "CT",
        display_address: ["138 Wooster St", "New Haven, CT 06511"],
      },
      phone: "+12037454194",
      display_phone: "(203) 745-4194",
      distance: 1309.0979232493744,
    },
    {
      id: "2C2e0zun--lruw-jkkv9cw",
      alias: "hachiroku-shokudo-and-sake-bar-new-haven",
      name: "Hachiroku Shokudo & Sake Bar",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/id0-x9FPcPwg_BS98JTsNQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/hachiroku-shokudo-and-sake-bar-new-haven?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 45,
      categories: [
        {
          alias: "tapas",
          title: "Tapas Bars",
        },
        {
          alias: "izakaya",
          title: "Izakaya",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 41.30796,
        longitude: -72.92231,
      },
      transactions: [],
      location: {
        address1: "261 Orange St",
        address2: null,
        address3: "",
        city: "New Haven",
        zip_code: "06510",
        country: "US",
        state: "CT",
        display_address: ["261 Orange St", "New Haven, CT 06510"],
      },
      phone: "+12036917984",
      display_phone: "(203) 691-7984",
      distance: 551.2681252756801,
    },
    {
      id: "jJQc__6MRxI_HMPBbM9okw",
      alias: "tavern-on-state-new-haven-4",
      name: "Tavern On State",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/7KN28HIlbmwmhEaekgrPbQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/tavern-on-state-new-haven-4?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 142,
      categories: [
        {
          alias: "tradamerican",
          title: "American (Traditional)",
        },
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 41.31529,
        longitude: -72.90987,
      },
      transactions: ["delivery"],
      location: {
        address1: "969 State St",
        address2: "",
        address3: null,
        city: "New Haven",
        zip_code: "06511",
        country: "US",
        state: "CT",
        display_address: ["969 State St", "New Haven, CT 06511"],
      },
      phone: "+14752026883",
      display_phone: "(475) 202-6883",
      distance: 1491.8606885833624,
    },
    {
      id: "0Cj2ldFtMo4NgTkR9eTzUw",
      alias: "villa-lulu-new-haven",
      name: "Villa Lulu",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/D3rBHkCQwrgFpVu6TZ6Eew/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/villa-lulu-new-haven?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 90,
      categories: [
        {
          alias: "italian",
          title: "Italian",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 41.30642,
        longitude: -72.92962,
      },
      transactions: ["pickup", "delivery"],
      location: {
        address1: "230 College St",
        address2: "",
        address3: null,
        city: "New Haven",
        zip_code: "06510",
        country: "US",
        state: "CT",
        display_address: ["230 College St", "New Haven, CT 06510"],
      },
      phone: "+12036917177",
      display_phone: "(203) 691-7177",
      distance: 593.7315721035461,
    },
    {
      id: "UiE-W9pDOSP3p4bYAgGXyw",
      alias: "september-in-bangkok-new-haven",
      name: "September In Bangkok",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/2_Eb7197IuVm1OashwMcKg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/september-in-bangkok-new-haven?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 390,
      categories: [
        {
          alias: "thai",
          title: "Thai",
        },
        {
          alias: "panasian",
          title: "Pan Asian",
        },
        {
          alias: "noodles",
          title: "Noodles",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 41.3118639681927,
        longitude: -72.9162034392357,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "754 State St",
        address2: null,
        address3: null,
        city: "New Haven",
        zip_code: "06511",
        country: "US",
        state: "CT",
        display_address: ["754 State St", "New Haven, CT 06511"],
      },
      phone: "+14752345239",
      display_phone: "(475) 234-5239",
      distance: 895.6114123134797,
    },
    {
      id: "GH5B8nQRXgX-eFy4xgtcXg",
      alias: "barracuda-bistro-and-bar-new-haven",
      name: "Barracuda Bistro & Bar",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/966ForKR7s6e1JYKhxLTXg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/barracuda-bistro-and-bar-new-haven?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 469,
      categories: [
        {
          alias: "latin",
          title: "Latin American",
        },
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
        {
          alias: "seafood",
          title: "Seafood",
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 41.30876,
        longitude: -72.93383,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "1180 Chapel St",
        address2: "",
        address3: "",
        city: "New Haven",
        zip_code: "06511",
        country: "US",
        state: "CT",
        display_address: ["1180 Chapel St", "New Haven, CT 06511"],
      },
      phone: "+12036915696",
      display_phone: "(203) 691-5696",
      distance: 635.6103812074273,
    },
    {
      id: "qxPTfJp-Lx1I_CcEM0H5Ig",
      alias: "elm-city-social-new-haven",
      name: "Elm City Social",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/5uK6-MfFH9oRd7bSvKf6IA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/elm-city-social-new-haven?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 447,
      categories: [
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
        {
          alias: "newamerican",
          title: "American (New)",
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 41.3070297241211,
        longitude: -72.9292297363281,
      },
      transactions: ["pickup"],
      price: "$$",
      location: {
        address1: "266 College St",
        address2: null,
        address3: "",
        city: "New Haven",
        zip_code: "06510",
        country: "US",
        state: "CT",
        display_address: ["266 College St", "New Haven, CT 06510"],
      },
      phone: "+14754417436",
      display_phone: "(475) 441-7436",
      distance: 516.7504558210492,
    },
    {
      id: "k2kbZ8f8VIpXdIv9NierGw",
      alias: "barcelona-new-haven-new-haven-3",
      name: "Barcelona - New Haven",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/NFDljlFu99MyKRT_uTmc9w/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/barcelona-new-haven-new-haven-3?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 709,
      categories: [
        {
          alias: "wine_bars",
          title: "Wine Bars",
        },
        {
          alias: "spanish",
          title: "Spanish",
        },
        {
          alias: "tapas",
          title: "Tapas Bars",
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 41.30571,
        longitude: -72.92722,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "155 Temple St",
        address2: "",
        address3: "",
        city: "New Haven",
        zip_code: "06510",
        country: "US",
        state: "CT",
        display_address: ["155 Temple St", "New Haven, CT 06510"],
      },
      phone: "+12038483000",
      display_phone: "(203) 848-3000",
      distance: 637.0001835247225,
    },
    {
      id: "oVMFDIHO6nj7aPrVzHVTJg",
      alias: "80-proof-american-kitchen-and-bar-new-haven-3",
      name: "80 Proof American Kitchen & Bar",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/_hPuxpijUFgKwsZjJ7UDZQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/80-proof-american-kitchen-and-bar-new-haven-3?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 66,
      categories: [
        {
          alias: "newamerican",
          title: "American (New)",
        },
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
        {
          alias: "venues",
          title: "Venues & Event Spaces",
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 41.30535,
        longitude: -72.92829,
      },
      transactions: [],
      price: "$$",
      location: {
        address1: "196 Crown St",
        address2: "",
        address3: null,
        city: "New Haven",
        zip_code: "06510",
        country: "US",
        state: "CT",
        display_address: ["196 Crown St", "New Haven, CT 06510"],
      },
      phone: "+12036917320",
      display_phone: "(203) 691-7320",
      distance: 704.6058820273164,
    },
    {
      id: "B6VlKBNeVpN4delxO2G_nA",
      alias: "shell-and-bones-oyster-bar-and-grill-new-haven-2",
      name: "Shell & Bones Oyster Bar and Grill",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/K1ic7Yim9AAOScmxOzR0tg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/shell-and-bones-oyster-bar-and-grill-new-haven-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 832,
      categories: [
        {
          alias: "seafood",
          title: "Seafood",
        },
        {
          alias: "steak",
          title: "Steakhouses",
        },
        {
          alias: "wine_bars",
          title: "Wine Bars",
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 41.280462628599174,
        longitude: -72.92943662740232,
      },
      transactions: ["pickup", "delivery"],
      price: "$$$",
      location: {
        address1: "100 S Water St",
        address2: "",
        address3: "",
        city: "New Haven",
        zip_code: "06519",
        country: "US",
        state: "CT",
        display_address: ["100 S Water St", "New Haven, CT 06519"],
      },
      phone: "+12037873466",
      display_phone: "(203) 787-3466",
      distance: 3438.609594935577,
    },
    {
      id: "AbSck6wtp-3zWvmsacAKSw",
      alias: "olea-new-haven-2",
      name: "Olea",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/VMKebj8XB15A8RdH6bYW6Q/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/olea-new-haven-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 178,
      categories: [
        {
          alias: "mediterranean",
          title: "Mediterranean",
        },
        {
          alias: "spanish",
          title: "Spanish",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 41.3073381516486,
        longitude: -72.9307242429901,
      },
      transactions: ["delivery"],
      price: "$$$",
      location: {
        address1: "39 High St",
        address2: "",
        address3: "",
        city: "New Haven",
        zip_code: "06510",
        country: "US",
        state: "CT",
        display_address: ["39 High St", "New Haven, CT 06510"],
      },
      phone: "+12037808925",
      display_phone: "(203) 780-8925",
      distance: 546.5555272964142,
    },
    {
      id: "wErUraefWOu8p2-G6C5p2g",
      alias: "sherkaan-indian-street-food-new-haven-2",
      name: "Sherkaan Indian Street Food",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/XijFPFJKWVr0VCaLb4A7UA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/sherkaan-indian-street-food-new-haven-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 319,
      categories: [
        {
          alias: "indpak",
          title: "Indian",
        },
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
        {
          alias: "beerbar",
          title: "Beer Bar",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 41.3120238388542,
        longitude: -72.9306862248807,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "65 Broadway",
        address2: null,
        address3: "",
        city: "New Haven",
        zip_code: "06511",
        country: "US",
        state: "CT",
        display_address: ["65 Broadway", "New Haven, CT 06511"],
      },
      phone: "+12034055808",
      display_phone: "(203) 405-5808",
      distance: 325.33077373987857,
    },
    {
      id: "9pKDBd-PihtiY_bUV8F69Q",
      alias: "nolo-new-haven-2",
      name: "NOLO",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/Wl5r7CJ-gFD6gVlimOjwtw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/nolo-new-haven-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 155,
      categories: [
        {
          alias: "tapasmallplates",
          title: "Tapas/Small Plates",
        },
        {
          alias: "italian",
          title: "Italian",
        },
        {
          alias: "pizza",
          title: "Pizza",
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 41.31012,
        longitude: -72.91748,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "687 State St",
        address2: "",
        address3: null,
        city: "New Haven",
        zip_code: "06511",
        country: "US",
        state: "CT",
        display_address: ["687 State St", "New Haven, CT 06511"],
      },
      phone: "+12038917704",
      display_phone: "(203) 891-7704",
      distance: 788.5807070109772,
    },
    {
      id: "rl8dyHsEpivQNOo69uUIIA",
      alias: "menya-gumi-new-haven",
      name: "Menya-Gumi",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/COkPdqX_yaDjUIQZ83atBg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/menya-gumi-new-haven?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 80,
      categories: [
        {
          alias: "ramen",
          title: "Ramen",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 41.306143,
        longitude: -72.9235414,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "165 Orange St",
        address2: "",
        address3: null,
        city: "New Haven",
        zip_code: "06510",
        country: "US",
        state: "CT",
        display_address: ["165 Orange St", "New Haven, CT 06510"],
      },
      phone: "+12035350302",
      display_phone: "(203) 535-0302",
      distance: 641.2894425200521,
    },
    {
      id: "JH7GsGhpUHgLLMMqLH4xTQ",
      alias: "bar-august-new-haven",
      name: "Bar August",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/TXzvDnPDstQ3OPjhAM-ATQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/bar-august-new-haven?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 150,
      categories: [
        {
          alias: "wine_bars",
          title: "Wine Bars",
        },
        {
          alias: "newamerican",
          title: "American (New)",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 41.315817573308,
        longitude: -72.9096213155399,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "3 Edwards St",
        address2: "",
        address3: "",
        city: "New Haven",
        zip_code: "06511",
        country: "US",
        state: "CT",
        display_address: ["3 Edwards St", "New Haven, CT 06511"],
      },
      phone: "+12037454531",
      display_phone: "(203) 745-4531",
      distance: 1527.224324894623,
    },
    {
      id: "3IukvOBg930-GuZ-70j3cQ",
      alias: "tibetan-kitchen-new-haven",
      name: "Tibetan Kitchen",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/YbIptz0Uc56m0BEnkN_paA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/tibetan-kitchen-new-haven?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 181,
      categories: [
        {
          alias: "himalayan",
          title: "Himalayan/Nepalese",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 41.5638227015734,
        longitude: -72.6517121493816,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "1217 Chapel St",
        address2: null,
        address3: "",
        city: "New Haven",
        zip_code: "06511",
        country: "US",
        state: "CT",
        display_address: ["1217 Chapel St", "New Haven, CT 06511"],
      },
      phone: "",
      display_phone: "",
      distance: 714.8630328735784,
    },
    {
      id: "WH9RT73x1nQj90zrUwJEpQ",
      alias: "oak-haven-table-and-bar-new-haven",
      name: "Oak Haven Table & Bar",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/Ef4LKg_weGE3cKAqtCfSDw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/oak-haven-table-and-bar-new-haven?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 366,
      categories: [
        {
          alias: "gastropubs",
          title: "Gastropubs",
        },
        {
          alias: "tapas",
          title: "Tapas Bars",
        },
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 41.3147897,
        longitude: -72.9110714,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "932 State St",
        address2: null,
        address3: "",
        city: "New Haven",
        zip_code: "06511",
        country: "US",
        state: "CT",
        display_address: ["932 State St", "New Haven, CT 06511"],
      },
      phone: "+12039159413",
      display_phone: "(203) 915-9413",
      distance: 1377.1190954375331,
    },
    {
      id: "mibVcv2Uh_1wMR0n6s1ouQ",
      alias: "te-amo-tequila-bar-and-tacos-new-haven",
      name: "Te Amo Tequila Bar & Tacos",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/ScjP82SVKFOsPKjLgSX9jg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/te-amo-tequila-bar-and-tacos-new-haven?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 306,
      categories: [
        {
          alias: "tacos",
          title: "Tacos",
        },
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
        {
          alias: "newmexican",
          title: "New Mexican Cuisine",
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 41.3063289013311,
        longitude: -72.9273620992899,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "182 Temple St",
        address2: "",
        address3: null,
        city: "New Haven",
        zip_code: "06510",
        country: "US",
        state: "CT",
        display_address: ["182 Temple St", "New Haven, CT 06510"],
      },
      phone: "+12035537914",
      display_phone: "(203) 553-7914",
      distance: 557.2149650296609,
    },
  ],
  total: 1100,
  region: {
    center: {
      longitude: -72.9269027709961,
      latitude: 41.31132816928134,
    },
  },
};
