export const data = {
  businesses: [
    {
      id: "MJEwQTtY9mzWJLCU7e25bw",
      alias: "draft-republic-san-marcos-san-marcos-2",
      name: "Draft Republic - San Marcos",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/I04V2yKBIZa43hdeGa9DYg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/draft-republic-san-marcos-san-marcos-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 306,
      categories: [
        {
          alias: "beergardens",
          title: "Beer Gardens",
        },
        {
          alias: "tradamerican",
          title: "American (Traditional)",
        },
        {
          alias: "gastropubs",
          title: "Gastropubs",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 33.1359,
        longitude: -117.15821,
      },
      transactions: [],
      price: "$$",
      location: {
        address1: "255 Redel Rd",
        address2: null,
        address3: null,
        city: "San Marcos",
        zip_code: "92078",
        country: "US",
        state: "CA",
        display_address: ["255 Redel Rd", "San Marcos, CA 92078"],
      },
      phone: "+17602903520",
      display_phone: "(760) 290-3520",
      distance: 1850.3058136270963,
    },
    {
      id: "3rqvZnEUbGIuCKHsBWLFLg",
      alias: "amalfi-cucina-italiana-san-marcos-2",
      name: "Amalfi Cucina Italiana",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/Zwx1mgr9gEc_oIpFG2EfpQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/amalfi-cucina-italiana-san-marcos-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 619,
      categories: [
        {
          alias: "italian",
          title: "Italian",
        },
        {
          alias: "pizza",
          title: "Pizza",
        },
        {
          alias: "bars",
          title: "Bars",
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 33.12392496202204,
        longitude: -117.20782744781258,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "1035 La Bonita Dr",
        address2: null,
        address3: null,
        city: "San Marcos",
        zip_code: "92078",
        country: "US",
        state: "CA",
        display_address: ["1035 La Bonita Dr", "San Marcos, CA 92078"],
      },
      phone: "+17606533230",
      display_phone: "(760) 653-3230",
      distance: 3241.313608912303,
    },
    {
      id: "SCrEOKR5uKHXo0a4BUsPhA",
      alias: "aria-restaurant-san-marcos",
      name: "Aria Restaurant",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/NOhBFyOZjxs78VybGoonkQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/aria-restaurant-san-marcos?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 137,
      categories: [
        {
          alias: "persian",
          title: "Persian/Iranian",
        },
        {
          alias: "mediterranean",
          title: "Mediterranean",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 33.14891,
        longitude: -117.19797,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "1650 Descanso Ave",
        address2: null,
        address3: "",
        city: "San Marcos",
        zip_code: "92078",
        country: "US",
        state: "CA",
        display_address: ["1650 Descanso Ave", "San Marcos, CA 92078"],
      },
      phone: "+17605397890",
      display_phone: "(760) 539-7890",
      distance: 2157.625933928102,
    },
    {
      id: "eGCM9QgCBlXM81kSo-g5DQ",
      alias: "stone-brewing-world-bistro-and-gardens-escondido-escondido-2",
      name: "Stone Brewing World Bistro & Gardens - Escondido",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/5xweQ_wt8f23Ief1unTQog/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/stone-brewing-world-bistro-and-gardens-escondido-escondido-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 5661,
      categories: [
        {
          alias: "breweries",
          title: "Breweries",
        },
        {
          alias: "newamerican",
          title: "American (New)",
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 33.116948079231,
        longitude: -117.119835988409,
      },
      transactions: [],
      price: "$$",
      location: {
        address1: "1999 Citracado Pkwy",
        address2: "",
        address3: "",
        city: "Escondido",
        zip_code: "92029",
        country: "US",
        state: "CA",
        display_address: ["1999 Citracado Pkwy", "Escondido, CA 92029"],
      },
      phone: "+17602947866",
      display_phone: "(760) 294-7866",
      distance: 5954.321561571984,
    },
    {
      id: "okfpAclrSbJCXt3854GOQA",
      alias: "up-in-smoke-bbq-san-marcos-3",
      name: "Up In Smoke BBQ",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/ghJEXGWVO9pCpPioLjbcLQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/up-in-smoke-bbq-san-marcos-3?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 555,
      categories: [
        {
          alias: "bbq",
          title: "Barbeque",
        },
        {
          alias: "newamerican",
          title: "American (New)",
        },
        {
          alias: "beerbar",
          title: "Beer Bar",
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 33.13501,
        longitude: -117.18554,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "925 W San Marcos Blvd",
        address2: null,
        address3: "",
        city: "San Marcos",
        zip_code: "92078",
        country: "US",
        state: "CA",
        display_address: ["925 W San Marcos Blvd", "San Marcos, CA 92078"],
      },
      phone: "+17602903532",
      display_phone: "(760) 290-3532",
      distance: 826.0909997066193,
    },
    {
      id: "PczpdcaqLR9EaGUcbqkS2w",
      alias: "buona-forchetta-san-marcos-san-marcos-2",
      name: "Buona Forchetta - San Marcos",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/XwaE_HMPYxHsOC7L1WSLCQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/buona-forchetta-san-marcos-san-marcos-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 257,
      categories: [
        {
          alias: "pizza",
          title: "Pizza",
        },
        {
          alias: "italian",
          title: "Italian",
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 33.13546739553502,
        longitude: -117.1593791,
      },
      transactions: [],
      price: "$$",
      location: {
        address1: "250 N City Dr",
        address2: "",
        address3: null,
        city: "San Marcos",
        zip_code: "92078",
        country: "US",
        state: "CA",
        display_address: ["250 N City Dr", "San Marcos, CA 92078"],
      },
      phone: "+14425153147",
      display_phone: "(442) 515-3147",
      distance: 1785.886278792327,
    },
    {
      id: "dYZliVGCfFDkTASYdsH4kA",
      alias: "pita-guys-san-marcos",
      name: "Pita Guys",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/XkmLRrWCcS4yvoYV_cMiow/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/pita-guys-san-marcos?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 1101,
      categories: [
        {
          alias: "mediterranean",
          title: "Mediterranean",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 33.139878289782374,
        longitude: -117.1625062,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "133 N Twin Oaks Valley Rd",
        address2: "Ste 104",
        address3: "",
        city: "San Marcos",
        zip_code: "92069",
        country: "US",
        state: "CA",
        display_address: [
          "133 N Twin Oaks Valley Rd",
          "Ste 104",
          "San Marcos, CA 92069",
        ],
      },
      phone: "+17605663040",
      display_phone: "(760) 566-3040",
      distance: 1452.4339007923704,
    },
    {
      id: "awGNkG9H3imdRVnvZBk8jw",
      alias: "eugenio-italian-ristorante-san-marcos",
      name: "Eugenio Italian Ristorante",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/MnFWqzq83Gq5NCRM-cDpbQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/eugenio-italian-ristorante-san-marcos?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 330,
      categories: [
        {
          alias: "italian",
          title: "Italian",
        },
        {
          alias: "pizza",
          title: "Pizza",
        },
        {
          alias: "wine_bars",
          title: "Wine Bars",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 33.131861,
        longitude: -117.205801,
      },
      transactions: ["restaurant_reservation"],
      price: "$$",
      location: {
        address1: "679 S Rancho Santa Fe Rd",
        address2: "",
        address3: null,
        city: "San Marcos",
        zip_code: "92078",
        country: "US",
        state: "CA",
        display_address: ["679 S Rancho Santa Fe Rd", "San Marcos, CA 92078"],
      },
      phone: "+17603046939",
      display_phone: "(760) 304-6939",
      distance: 2699.755232988619,
    },
    {
      id: "tqjS0NLuXpNQ0D_eeE_ghA",
      alias: "padadak-san-marcos",
      name: "Padadak",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/q45lb3g-JMqOqmFNeXzi-A/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/padadak-san-marcos?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 54,
      categories: [
        {
          alias: "korean",
          title: "Korean",
        },
        {
          alias: "chicken_wings",
          title: "Chicken Wings",
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 33.1359,
        longitude: -117.17819,
      },
      transactions: [],
      price: "$$",
      location: {
        address1: "595 Grand Ave",
        address2: "Ste 105",
        address3: null,
        city: "San Marcos",
        zip_code: "92078",
        country: "US",
        state: "CA",
        display_address: ["595 Grand Ave", "Ste 105", "San Marcos, CA 92078"],
      },
      phone: "+17605397104",
      display_phone: "(760) 539-7104",
      distance: 329.06625838084244,
    },
    {
      id: "UFTbRgYpjDz2OLLJrmS9tA",
      alias: "the-bellows-san-marcos-2",
      name: "The Bellows",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/I8a9sCVGSSVwKc5lP5E4YQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/the-bellows-san-marcos-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 596,
      categories: [
        {
          alias: "gastropubs",
          title: "Gastropubs",
        },
        {
          alias: "tradamerican",
          title: "American (Traditional)",
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 33.122944,
        longitude: -117.165618,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "803 S Twin Oaks Valley Rd",
        address2: "Ste 107",
        address3: "",
        city: "San Marcos",
        zip_code: "92078",
        country: "US",
        state: "CA",
        display_address: [
          "803 S Twin Oaks Valley Rd",
          "Ste 107",
          "San Marcos, CA 92078",
        ],
      },
      phone: "+17602903912",
      display_phone: "(760) 290-3912",
      distance: 2134.2258372803135,
    },
    {
      id: "idfNjUwsnIP21xuxNouXAw",
      alias: "thai-thai-san-marcos-restaurant-san-marcos",
      name: "Thai Thai San Marcos Restaurant",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/uzD7chBogrREey_ckPJFog/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/thai-thai-san-marcos-restaurant-san-marcos?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 138,
      categories: [
        {
          alias: "thai",
          title: "Thai",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 33.12334391319446,
        longitude: -117.16568624216544,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "801 S Twin Oaks Valley Rd",
        address2: "Unit 101",
        address3: "",
        city: "San Marcos",
        zip_code: "92078",
        country: "US",
        state: "CA",
        display_address: [
          "801 S Twin Oaks Valley Rd",
          "Unit 101",
          "San Marcos, CA 92078",
        ],
      },
      phone: "+14425153240",
      display_phone: "(442) 515-3240",
      distance: 2093.5280974203692,
    },
    {
      id: "VknIQhhb1d6I9-E15dInPw",
      alias: "las-brisas-mexican-cuisine-san-marcos",
      name: "Las Brisas Mexican Cuisine",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/IG7AHg9i_ZTxOKx7wbmhBw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/las-brisas-mexican-cuisine-san-marcos?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 888,
      categories: [
        {
          alias: "mexican",
          title: "Mexican",
        },
        {
          alias: "seafood",
          title: "Seafood",
        },
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 33.13491,
        longitude: -117.20545,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "577 S Rancho Santa Fe Rd",
        address2: "Ste 105",
        address3: "",
        city: "San Marcos",
        zip_code: "92078",
        country: "US",
        state: "CA",
        display_address: [
          "577 S Rancho Santa Fe Rd",
          "Ste 105",
          "San Marcos, CA 92078",
        ],
      },
      phone: "+17607989906",
      display_phone: "(760) 798-9906",
      distance: 2573.82940500292,
    },
    {
      id: "vvjwHi1gqO6OzLnXoxA-wg",
      alias: "ramen-mik-san-marcos-2",
      name: "Ramen Mik",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/hCgSzTJj9ebAfElCsKpvyw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/ramen-mik-san-marcos-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 88,
      categories: [
        {
          alias: "ramen",
          title: "Ramen",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 33.14011,
        longitude: -117.16362,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "157 N Twin Oaks Valley Rd",
        address2: "Ste 132",
        address3: null,
        city: "San Marcos",
        zip_code: "92069",
        country: "US",
        state: "CA",
        display_address: [
          "157 N Twin Oaks Valley Rd",
          "Ste 132",
          "San Marcos, CA 92069",
        ],
      },
      phone: "+17607604334",
      display_phone: "(760) 760-4334",
      distance: 1407.14335812442,
    },
    {
      id: "3rnbBCOmglTMZPKGPjJE-Q",
      alias: "tabu-shabu-bressi-ranch-carlsbad-2",
      name: "Tabu Shabu - Bressi Ranch",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/5G628F0FoJj1ER6s0RfVsA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/tabu-shabu-bressi-ranch-carlsbad-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 289,
      categories: [
        {
          alias: "japanese",
          title: "Japanese",
        },
        {
          alias: "hotpot",
          title: "Hot Pot",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 33.1275049,
        longitude: -117.2534231,
      },
      transactions: ["pickup"],
      price: "$$$",
      location: {
        address1: "2674 Gateway Rd",
        address2: "Ste 190",
        address3: null,
        city: "Carlsbad",
        zip_code: "92009",
        country: "US",
        state: "CA",
        display_address: ["2674 Gateway Rd", "Ste 190", "Carlsbad, CA 92009"],
      },
      phone: "+17608460778",
      display_phone: "(760) 846-0778",
      distance: 7093.367367427923,
    },
    {
      id: "wVRAPwQOsgHy3we_EyXvMQ",
      alias: "madera-kitchen-of-mexico-vista",
      name: "Madera Kitchen of Mexico",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/DFinMLkzx0jzhtp8svrWCA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/madera-kitchen-of-mexico-vista?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 289,
      categories: [
        {
          alias: "mexican",
          title: "Mexican",
        },
        {
          alias: "beer_and_wine",
          title: "Beer, Wine & Spirits",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 33.18662,
        longitude: -117.22425,
      },
      transactions: ["restaurant_reservation", "pickup", "delivery"],
      price: "$$",
      location: {
        address1: "1250 S Santa Fe Ave",
        address2: "",
        address3: null,
        city: "Vista",
        zip_code: "92084",
        country: "US",
        state: "CA",
        display_address: ["1250 S Santa Fe Ave", "Vista, CA 92084"],
      },
      phone: "+17608840429",
      display_phone: "(760) 884-0429",
      distance: 6856.59437653024,
    },
    {
      id: "tkQS0Ffox1NKL4p8ISVzPA",
      alias: "manna-korean-bbq-san-marcos",
      name: "Manna Korean BBQ",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/udLGgSWc-uEJjBTjgACeeA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/manna-korean-bbq-san-marcos?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 1441,
      categories: [
        {
          alias: "korean",
          title: "Korean",
        },
        {
          alias: "bbq",
          title: "Barbeque",
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 33.1344023,
        longitude: -117.1197782,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "740 Nordahl Rd",
        address2: "",
        address3: "",
        city: "San Marcos",
        zip_code: "92069",
        country: "US",
        state: "CA",
        display_address: ["740 Nordahl Rd", "San Marcos, CA 92069"],
      },
      phone: "+17607433300",
      display_phone: "(760) 743-3300",
      distance: 5509.005028094335,
    },
    {
      id: "HDxZrkGVu0FzjQPjFgeLpg",
      alias: "o-prego-a-taste-of-portugal-and-brazil-san-marcos",
      name: "O Prego - A Taste of Portugal & Brazil ",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/viCccR4BnyOgbDcrkQCc9Q/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/o-prego-a-taste-of-portugal-and-brazil-san-marcos?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 15,
      categories: [
        {
          alias: "portuguese",
          title: "Portuguese",
        },
        {
          alias: "importedfood",
          title: "Imported Food",
        },
        {
          alias: "brazilian",
          title: "Brazilian",
        },
      ],
      rating: 5,
      coordinates: {
        latitude: 33.14154,
        longitude: -117.18541,
      },
      transactions: [],
      location: {
        address1: "980 Los Vallecitos Blvd",
        address2: null,
        address3: "",
        city: "San Marcos",
        zip_code: "92069",
        country: "US",
        state: "CA",
        display_address: ["980 Los Vallecitos Blvd", "San Marcos, CA 92069"],
      },
      phone: "+16198824215",
      display_phone: "(619) 882-4215",
      distance: 740.05082654753,
    },
    {
      id: "R8GAzKSeKroz0_WItzLGfw",
      alias: "flavor-of-himalaya-san-marcos-8",
      name: "Flavor of Himalaya",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/a7L7xAYKX2JlJf1gopZB8w/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/flavor-of-himalaya-san-marcos-8?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 272,
      categories: [
        {
          alias: "indpak",
          title: "Indian",
        },
        {
          alias: "himalayan",
          title: "Himalayan/Nepalese",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 33.13616624236802,
        longitude: -117.18001856129119,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "727 W San Marcos Blvd 115-116",
        address2: "Ste 115-116",
        address3: "",
        city: "San Marcos",
        zip_code: "92078",
        country: "US",
        state: "CA",
        display_address: [
          "727 W San Marcos Blvd 115-116",
          "Ste 115-116",
          "San Marcos, CA 92078",
        ],
      },
      phone: "+17605397184",
      display_phone: "(760) 539-7184",
      distance: 368.7388667361224,
    },
    {
      id: "0235KxAvFT4vV_QSwc1HYA",
      alias: "two-hands-corn-dog-san-marcos-san-marcos",
      name: "Two Hands Corn Dog - San Marcos",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/5_7Ncktt4_gS1CrtNBua-w/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/two-hands-corn-dog-san-marcos-san-marcos?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 85,
      categories: [
        {
          alias: "korean",
          title: "Korean",
        },
        {
          alias: "hotdog",
          title: "Hot Dogs",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 33.13443,
        longitude: -117.18742,
      },
      transactions: ["pickup", "delivery"],
      price: "$",
      location: {
        address1: "997 W San Marcos Blvd",
        address2: "Ste 107",
        address3: "",
        city: "San Marcos",
        zip_code: "92078",
        country: "US",
        state: "CA",
        display_address: [
          "997 W San Marcos Blvd",
          "Ste 107",
          "San Marcos, CA 92078",
        ],
      },
      phone: "+17602903068",
      display_phone: "(760) 290-3068",
      distance: 993.3406253094691,
    },
    {
      id: "9qJrsHctBfV1paYZF06qbQ",
      alias: "old-california-mining-san-marcos-5",
      name: "Old California Mining",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/d2T69Kpzv8mpyymhQMsCYw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/old-california-mining-san-marcos-5?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ",
      review_count: 113,
      categories: [
        {
          alias: "tradamerican",
          title: "American (Traditional)",
        },
        {
          alias: "seafood",
          title: "Seafood",
        },
        {
          alias: "breakfast_brunch",
          title: "Breakfast & Brunch",
        },
      ],
      rating: 3.5,
      coordinates: {
        latitude: 33.135358,
        longitude: -117.189559,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "1020 W San Marcos Blvd",
        address2: "Ste 118",
        address3: null,
        city: "San Marcos",
        zip_code: "92078",
        country: "US",
        state: "CA",
        display_address: [
          "1020 W San Marcos Blvd",
          "Ste 118",
          "San Marcos, CA 92078",
        ],
      },
      phone: "+17607614900",
      display_phone: "(760) 761-4900",
      distance: 1145.6274536753049,
    },
  ],
  total: 1100,
  region: {
    center: {
      longitude: -117.17811584472656,
      latitude: 33.13897801118074,
    },
  },
};
