export const party = {
  _id: '64650461d9d4de0a410b407f',
  name: "Nate's Party",
  restaurants: [
    {
      id: 'MJEwQTtY9mzWJLCU7e25bw',
      alias: 'draft-republic-san-marcos-san-marcos-2',
      name: 'Draft Republic - San Marcos',
      image_url:
        'https://s3-media2.fl.yelpcdn.com/bphoto/I04V2yKBIZa43hdeGa9DYg/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/draft-republic-san-marcos-san-marcos-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
      review_count: 316,
      categories: [
        {
          alias: 'beergardens',
          title: 'Beer Gardens',
        },
        {
          alias: 'tradamerican',
          title: 'American (Traditional)',
        },
        {
          alias: 'gastropubs',
          title: 'Gastropubs',
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 33.1359,
        longitude: -117.15821,
      },
      transactions: [],
      price: '$$',
      location: {
        address1: '255 Redel Rd',
        address2: null,
        address3: null,
        city: 'San Marcos',
        zip_code: '92078',
        country: 'US',
        state: 'CA',
        display_address: ['255 Redel Rd', 'San Marcos, CA 92078'],
      },
      phone: '+17602903520',
      display_phone: '(760) 290-3520',
      distance: 1853.7821535245944,
      checked: true,
    },
    {
      id: '3rqvZnEUbGIuCKHsBWLFLg',
      alias: 'amalfi-cucina-italiana-san-marcos-2',
      name: 'Amalfi Cucina Italiana',
      image_url:
        'https://s3-media3.fl.yelpcdn.com/bphoto/Zwx1mgr9gEc_oIpFG2EfpQ/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/amalfi-cucina-italiana-san-marcos-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
      review_count: 641,
      categories: [
        {
          alias: 'italian',
          title: 'Italian',
        },
        {
          alias: 'pizza',
          title: 'Pizza',
        },
        {
          alias: 'bars',
          title: 'Bars',
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 33.12392496202204,
        longitude: -117.20782744781258,
      },
      transactions: ['delivery', 'pickup'],
      price: '$$',
      location: {
        address1: '1035 La Bonita Dr',
        address2: null,
        address3: null,
        city: 'San Marcos',
        zip_code: '92078',
        country: 'US',
        state: 'CA',
        display_address: ['1035 La Bonita Dr', 'San Marcos, CA 92078'],
      },
      phone: '+17606533230',
      display_phone: '(760) 653-3230',
      distance: 3235.8926326354317,
      checked: true,
    },
    {
      id: 'okfpAclrSbJCXt3854GOQA',
      alias: 'up-in-smoke-bbq-san-marcos-3',
      name: 'Up In Smoke BBQ',
      image_url:
        'https://s3-media2.fl.yelpcdn.com/bphoto/ghJEXGWVO9pCpPioLjbcLQ/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/up-in-smoke-bbq-san-marcos-3?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
      review_count: 559,
      categories: [
        {
          alias: 'bbq',
          title: 'Barbeque',
        },
        {
          alias: 'newamerican',
          title: 'American (New)',
        },
        {
          alias: 'beerbar',
          title: 'Beer Bar',
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 33.13501,
        longitude: -117.18554,
      },
      transactions: ['delivery', 'pickup'],
      price: '$$',
      location: {
        address1: '925 W San Marcos Blvd',
        address2: null,
        address3: '',
        city: 'San Marcos',
        zip_code: '92078',
        country: 'US',
        state: 'CA',
        display_address: ['925 W San Marcos Blvd', 'San Marcos, CA 92078'],
      },
      phone: '+17602903532',
      display_phone: '(760) 290-3532',
      distance: 820.6378289749948,
      checked: true,
    },
    {
      id: 'SCrEOKR5uKHXo0a4BUsPhA',
      alias: 'aria-restaurant-san-marcos',
      name: 'Aria Restaurant',
      image_url:
        'https://s3-media2.fl.yelpcdn.com/bphoto/NOhBFyOZjxs78VybGoonkQ/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/aria-restaurant-san-marcos?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
      review_count: 139,
      categories: [
        {
          alias: 'persian',
          title: 'Persian/Iranian',
        },
        {
          alias: 'mediterranean',
          title: 'Mediterranean',
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 33.14891,
        longitude: -117.19797,
      },
      transactions: ['delivery', 'pickup'],
      price: '$$',
      location: {
        address1: '1650 Descanso Ave',
        address2: null,
        address3: '',
        city: 'San Marcos',
        zip_code: '92078',
        country: 'US',
        state: 'CA',
        display_address: ['1650 Descanso Ave', 'San Marcos, CA 92078'],
      },
      phone: '+17605397890',
      display_phone: '(760) 539-7890',
      distance: 2155.7905769225304,
      checked: true,
    },
  ],
  votes: {
    MJEwQTtY9mzWJLCU7e25bw: 3,
    '3rqvZnEUbGIuCKHsBWLFLg': 2,
    okfpAclrSbJCXt3854GOQA: 1,
    SCrEOKR5uKHXo0a4BUsPhA: 4,
  },
  password: 'ddd',
  maxVoters: 5,
  voters: 0,
  voteTime: true,
  hours: {
    '7-8 AM': 1,
    '8-9 AM': 2,
    '9-10 AM': 1,
    '10-11 AM': 4,
  },
  location: 'San Marcos',
  max_distance: 15000,
  number_of_restaurants: 5,
  createdAt: '2023-05-17T16:44:17.657Z',
  updatedAt: '2023-05-17T16:44:17.657Z',
  __v: 0,
};
