export const restaurants = [
  {
    id: 'MJEwQTtY9mzWJLCU7e25bw',
    alias: 'draft-republic-san-marcos-san-marcos-2',
    name: 'Draft Republic - San Marcos',
    image_url:
      'https://s3-media2.fl.yelpcdn.com/bphoto/I04V2yKBIZa43hdeGa9DYg/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/draft-republic-san-marcos-san-marcos-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
    review_count: 316,
    categories: [
      {
        alias: 'beergardens',
        title: 'Beer Gardens',
      },
      {
        alias: 'tradamerican',
        title: 'American (Traditional)',
      },
      {
        alias: 'gastropubs',
        title: 'Gastropubs',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 33.1359,
      longitude: -117.15821,
    },
    transactions: [],
    price: '$$',
    location: {
      address1: '255 Redel Rd',
      address2: null,
      address3: null,
      city: 'San Marcos',
      zip_code: '92078',
      country: 'US',
      state: 'CA',
      display_address: ['255 Redel Rd', 'San Marcos, CA 92078'],
    },
    phone: '+17602903520',
    display_phone: '(760) 290-3520',
    distance: 1852.4602322497708,
  },
  {
    id: 'DhrUPGkVW7_AzY3spH74-Q',
    alias: 'cow-shed-bar-and-grill-san-marcos-2',
    name: 'Cow Shed Bar & Grill',
    image_url:
      'https://s3-media2.fl.yelpcdn.com/bphoto/enc4fTjj81jRSuyiFmarnw/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/cow-shed-bar-and-grill-san-marcos-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
    review_count: 188,
    categories: [
      {
        alias: 'danceclubs',
        title: 'Dance Clubs',
      },
      {
        alias: 'divebars',
        title: 'Dive Bars',
      },
      {
        alias: 'musicvenues',
        title: 'Music Venues',
      },
    ],
    rating: 3,
    coordinates: {
      latitude: 33.14467,
      longitude: -117.15228,
    },
    transactions: ['delivery'],
    price: '$',
    location: {
      address1: '502 E Mission Rd',
      address2: '',
      address3: '',
      city: 'San Marcos',
      zip_code: '92069',
      country: 'US',
      state: 'CA',
      display_address: ['502 E Mission Rd', 'San Marcos, CA 92069'],
    },
    phone: '+17604712939',
    display_phone: '(760) 471-2939',
    distance: 2477.722122118412,
  },
  {
    id: 'AfcKpMu7H4jCMhfNJMhZiA',
    alias: 'frankies-escondido',
    name: 'Frankies',
    image_url:
      'https://s3-media4.fl.yelpcdn.com/bphoto/U90Uo9bn31YERWK2ExTELw/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/frankies-escondido?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
    review_count: 31,
    categories: [
      {
        alias: 'sportsbars',
        title: 'Sports Bars',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 33.15839,
      longitude: -117.09998,
    },
    transactions: [],
    location: {
      address1: '555 W Country Club Ln',
      address2: 'Ste F',
      address3: null,
      city: 'Escondido',
      zip_code: '92026',
      country: 'US',
      state: 'CA',
      display_address: [
        '555 W Country Club Ln',
        'Ste F',
        'Escondido, CA 92026',
      ],
    },
    phone: '+17602918319',
    display_phone: '(760) 291-8319',
    distance: 7587.77586414808,
  },
  {
    id: 'fHY69HplC3Y_f00h2qBrOQ',
    alias: 'churchills-pub-and-grille-san-marcos',
    name: "Churchill's Pub & Grille",
    image_url:
      'https://s3-media2.fl.yelpcdn.com/bphoto/tMoGKp0jLHxZ0x99A1uq6A/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/churchills-pub-and-grille-san-marcos?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
    review_count: 905,
    categories: [
      {
        alias: 'pubs',
        title: 'Pubs',
      },
      {
        alias: 'tradamerican',
        title: 'American (Traditional)',
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 33.135409,
      longitude: -117.184703,
    },
    transactions: ['pickup', 'delivery'],
    price: '$$',
    location: {
      address1: '887 W San Marcos Blvd',
      address2: '',
      address3: '',
      city: 'San Marcos',
      zip_code: '92078',
      country: 'US',
      state: 'CA',
      display_address: ['887 W San Marcos Blvd', 'San Marcos, CA 92078'],
    },
    phone: '+17604718773',
    display_phone: '(760) 471-8773',
    distance: 730.5287716552791,
  },
  {
    id: 'UFTbRgYpjDz2OLLJrmS9tA',
    alias: 'the-bellows-san-marcos-2',
    name: 'The Bellows',
    image_url:
      'https://s3-media4.fl.yelpcdn.com/bphoto/I8a9sCVGSSVwKc5lP5E4YQ/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/the-bellows-san-marcos-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
    review_count: 598,
    categories: [
      {
        alias: 'gastropubs',
        title: 'Gastropubs',
      },
      {
        alias: 'tradamerican',
        title: 'American (Traditional)',
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 33.122944,
      longitude: -117.165618,
    },
    transactions: ['delivery'],
    price: '$$',
    location: {
      address1: '803 S Twin Oaks Valley Rd',
      address2: 'Ste 107',
      address3: '',
      city: 'San Marcos',
      zip_code: '92078',
      country: 'US',
      state: 'CA',
      display_address: [
        '803 S Twin Oaks Valley Rd',
        'Ste 107',
        'San Marcos, CA 92078',
      ],
    },
    phone: '+17602903912',
    display_phone: '(760) 290-3912',
    distance: 2129.1015635728095,
  },
  {
    id: 'h2-gVajLmCrYfRslCzcD3g',
    alias: 'black-plague-purgatory-lounge-escondido',
    name: 'Black Plague Purgatory Lounge',
    image_url:
      'https://s3-media4.fl.yelpcdn.com/bphoto/RQ6J2J2DOQq-M2wj5AR0Kg/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/black-plague-purgatory-lounge-escondido?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
    review_count: 33,
    categories: [
      {
        alias: 'beerbar',
        title: 'Beer Bar',
      },
      {
        alias: 'breweries',
        title: 'Breweries',
      },
    ],
    rating: 5,
    coordinates: {
      latitude: 33.12342,
      longitude: -117.07979,
    },
    transactions: [],
    price: '$$',
    location: {
      address1: '239 E Valley Pkwy',
      address2: null,
      address3: '',
      city: 'Escondido',
      zip_code: '92025',
      country: 'US',
      state: 'CA',
      display_address: ['239 E Valley Pkwy', 'Escondido, CA 92025'],
    },
    phone: '+17606318110',
    display_phone: '(760) 631-8110',
    distance: 9313.891960821453,
  },
  {
    id: 'VknIQhhb1d6I9-E15dInPw',
    alias: 'las-brisas-mexican-cuisine-san-marcos',
    name: 'Las Brisas Mexican Cuisine',
    image_url:
      'https://s3-media1.fl.yelpcdn.com/bphoto/IG7AHg9i_ZTxOKx7wbmhBw/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/las-brisas-mexican-cuisine-san-marcos?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
    review_count: 889,
    categories: [
      {
        alias: 'mexican',
        title: 'Mexican',
      },
      {
        alias: 'seafood',
        title: 'Seafood',
      },
      {
        alias: 'cocktailbars',
        title: 'Cocktail Bars',
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 33.13491,
      longitude: -117.20545,
    },
    transactions: ['pickup', 'delivery'],
    price: '$$',
    location: {
      address1: '577 S Rancho Santa Fe Rd',
      address2: 'Ste 105',
      address3: '',
      city: 'San Marcos',
      zip_code: '92078',
      country: 'US',
      state: 'CA',
      display_address: [
        '577 S Rancho Santa Fe Rd',
        'Ste 105',
        'San Marcos, CA 92078',
      ],
    },
    phone: '+17607989906',
    display_phone: '(760) 798-9906',
    distance: 2568.541243305757,
  },
  {
    id: '0mm9qQE4ir7WrNVGQtmD5g',
    alias: 'players-sports-bar-san-marcos',
    name: 'Players Sports Bar',
    image_url:
      'https://s3-media1.fl.yelpcdn.com/bphoto/PR-OLbun60FT4gI0Ow4qfA/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/players-sports-bar-san-marcos?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
    review_count: 357,
    categories: [
      {
        alias: 'sportsbars',
        title: 'Sports Bars',
      },
      {
        alias: 'tradamerican',
        title: 'American (Traditional)',
      },
    ],
    rating: 3,
    coordinates: {
      latitude: 33.130046391757,
      longitude: -117.16533746007,
    },
    transactions: ['pickup', 'delivery'],
    price: '$$',
    location: {
      address1: '328 S Twin Oaks Valley Rd',
      address2: '',
      address3: '',
      city: 'San Marcos',
      zip_code: '92078',
      country: 'US',
      state: 'CA',
      display_address: ['328 S Twin Oaks Valley Rd', 'San Marcos, CA 92078'],
    },
    phone: '+17607364272',
    display_phone: '(760) 736-4272',
    distance: 1549.85868023225,
  },
  {
    id: 'okfpAclrSbJCXt3854GOQA',
    alias: 'up-in-smoke-bbq-san-marcos-3',
    name: 'Up In Smoke BBQ',
    image_url:
      'https://s3-media2.fl.yelpcdn.com/bphoto/ghJEXGWVO9pCpPioLjbcLQ/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/up-in-smoke-bbq-san-marcos-3?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
    review_count: 559,
    categories: [
      {
        alias: 'bbq',
        title: 'Barbeque',
      },
      {
        alias: 'newamerican',
        title: 'American (New)',
      },
      {
        alias: 'beerbar',
        title: 'Beer Bar',
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 33.13501,
      longitude: -117.18554,
    },
    transactions: ['pickup', 'delivery'],
    price: '$$',
    location: {
      address1: '925 W San Marcos Blvd',
      address2: null,
      address3: '',
      city: 'San Marcos',
      zip_code: '92078',
      country: 'US',
      state: 'CA',
      display_address: ['925 W San Marcos Blvd', 'San Marcos, CA 92078'],
    },
    phone: '+17602903532',
    display_phone: '(760) 290-3532',
    distance: 818.1157737054409,
  },
  {
    id: 'cddCIpWLfUV82PkmvQHxcg',
    alias: 'colab-public-house-vista-2',
    name: 'Colab Public House',
    image_url:
      'https://s3-media3.fl.yelpcdn.com/bphoto/ImfPdBqpvvY7usOyzsFOaA/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/colab-public-house-vista-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
    review_count: 79,
    categories: [
      {
        alias: 'brewpubs',
        title: 'Brewpubs',
      },
      {
        alias: 'burgers',
        title: 'Burgers',
      },
      {
        alias: 'wine_bars',
        title: 'Wine Bars',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 33.16924951799316,
      longitude: -117.2202158694797,
    },
    transactions: [],
    price: '$$',
    location: {
      address1: '2129 Industrial Ct',
      address2: '',
      address3: null,
      city: 'Vista',
      zip_code: '92081',
      country: 'US',
      state: 'CA',
      display_address: ['2129 Industrial Ct', 'Vista, CA 92081'],
    },
    phone: '',
    display_phone: '',
    distance: 5166.266730795839,
  },
  {
    id: '7bMq05WXDgPZMhmWd5xaHQ',
    alias: '508-tavern-vista',
    name: '508 Tavern',
    image_url:
      'https://s3-media3.fl.yelpcdn.com/bphoto/vKKR3sxCzYVkhjg59Jc2bw/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/508-tavern-vista?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
    review_count: 310,
    categories: [
      {
        alias: 'bars',
        title: 'Bars',
      },
      {
        alias: 'tradamerican',
        title: 'American (Traditional)',
      },
    ],
    rating: 5,
    coordinates: {
      latitude: 33.1973462031604,
      longitude: -117.239446900785,
    },
    transactions: ['pickup', 'delivery'],
    price: '$$',
    location: {
      address1: '508 South Santa Fe Ave',
      address2: '',
      address3: null,
      city: 'Vista',
      zip_code: '92084',
      country: 'US',
      state: 'CA',
      display_address: ['508 South Santa Fe Ave', 'Vista, CA 92084'],
    },
    phone: '+17602950707',
    display_phone: '(760) 295-0707',
    distance: 8643.538684519373,
  },
  {
    id: 'g52rUywY2_pyxpqUpBZXyw',
    alias: 'inland-tavern-san-marcos',
    name: 'Inland Tavern',
    image_url:
      'https://s3-media1.fl.yelpcdn.com/bphoto/gcEIeIlWrP27eP7xJxF2lw/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/inland-tavern-san-marcos?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
    review_count: 268,
    categories: [
      {
        alias: 'tradamerican',
        title: 'American (Traditional)',
      },
      {
        alias: 'sportsbars',
        title: 'Sports Bars',
      },
    ],
    rating: 3.5,
    coordinates: {
      latitude: 33.133991,
      longitude: -117.188377,
    },
    transactions: ['pickup', 'delivery'],
    price: '$$',
    location: {
      address1: '1001 W San Marcos Blvd',
      address2: '',
      address3: '',
      city: 'San Marcos',
      zip_code: '92078',
      country: 'US',
      state: 'CA',
      display_address: ['1001 W San Marcos Blvd', 'San Marcos, CA 92078'],
    },
    phone: '+17607448782',
    display_phone: '(760) 744-8782',
    distance: 1131.8491458144113,
  },
  {
    id: '9aGHwsrQoaVyM3r08cPRkA',
    alias: '55-yard-line-san-marcos',
    name: '55 Yard Line',
    image_url:
      'https://s3-media4.fl.yelpcdn.com/bphoto/vLu77Ldg_cWBg8ktH5wMuw/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/55-yard-line-san-marcos?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
    review_count: 255,
    categories: [
      {
        alias: 'sportsbars',
        title: 'Sports Bars',
      },
      {
        alias: 'burgers',
        title: 'Burgers',
      },
    ],
    rating: 3.5,
    coordinates: {
      latitude: 33.13518070312257,
      longitude: -117.18941965501527,
    },
    transactions: ['delivery'],
    price: '$$',
    location: {
      address1: '1020 W San Marcos Blvd',
      address2: 'Ste 114',
      address3: '',
      city: 'San Marcos',
      zip_code: '92078',
      country: 'US',
      state: 'CA',
      display_address: [
        '1020 W San Marcos Blvd',
        'Ste 114',
        'San Marcos, CA 92078',
      ],
    },
    phone: '+17607441960',
    display_phone: '(760) 744-1960',
    distance: 1134.0434055050785,
  },
  {
    id: 'yGrwbZsQ8okv2KSgw0SUYQ',
    alias: 'north-bar-escondido',
    name: 'North Bar',
    image_url:
      'https://s3-media3.fl.yelpcdn.com/bphoto/dfzCRkZ9UjGLMTOnTDkgKw/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/north-bar-escondido?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
    review_count: 69,
    categories: [
      {
        alias: 'sportsbars',
        title: 'Sports Bars',
      },
      {
        alias: 'divebars',
        title: 'Dive Bars',
      },
    ],
    rating: 3.5,
    coordinates: {
      latitude: 33.1394056,
      longitude: -117.091816,
    },
    transactions: [],
    price: '$',
    location: {
      address1: '200 W El Norte Pkwy',
      address2: 'Ste 7',
      address3: '',
      city: 'Escondido',
      zip_code: '92026',
      country: 'US',
      state: 'CA',
      display_address: ['200 W El Norte Pkwy', 'Ste 7', 'Escondido, CA 92026'],
    },
    phone: '+17604808228',
    display_phone: '(760) 480-8228',
    distance: 8039.792617128028,
  },
  {
    id: 'KUDCBYhlo6WziD44yIGudg',
    alias: 'side-yard-public-house-escondido',
    name: 'Side Yard Public House',
    image_url:
      'https://s3-media2.fl.yelpcdn.com/bphoto/MKXKmypq7mv3xeVVlE1JFA/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/side-yard-public-house-escondido?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
    review_count: 123,
    categories: [
      {
        alias: 'sportsbars',
        title: 'Sports Bars',
      },
      {
        alias: 'burgers',
        title: 'Burgers',
      },
      {
        alias: 'sandwiches',
        title: 'Sandwiches',
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 33.21610093563496,
      longitude: -117.10936576120316,
    },
    transactions: [],
    price: '$$',
    location: {
      address1: '10326 Meadow Glen Way E',
      address2: '',
      address3: null,
      city: 'Escondido',
      zip_code: '92026',
      country: 'US',
      state: 'CA',
      display_address: ['10326 Meadow Glen Way E', 'Escondido, CA 92026'],
    },
    phone: '+17602971051',
    display_phone: '(760) 297-1051',
    distance: 10699.614705137894,
  },
  {
    id: 'Bh3o2pkbbCp1RbtN8EoQlA',
    alias: 'blu-social-lounge-rancho-santa-fe',
    name: 'Blu Social Lounge',
    image_url:
      'https://s3-media3.fl.yelpcdn.com/bphoto/SkEuECSkvyXGb88ueyPp9w/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/blu-social-lounge-rancho-santa-fe?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
    review_count: 1,
    categories: [
      {
        alias: 'lounges',
        title: 'Lounges',
      },
      {
        alias: 'cocktailbars',
        title: 'Cocktail Bars',
      },
      {
        alias: 'wine_bars',
        title: 'Wine Bars',
      },
    ],
    rating: 5,
    coordinates: {
      latitude: 33.02056,
      longitude: -117.20299,
    },
    transactions: [],
    location: {
      address1: '6106 Paseo Delicias',
      address2: null,
      address3: '',
      city: 'Rancho Santa Fe',
      zip_code: '92067',
      country: 'US',
      state: 'CA',
      display_address: ['6106 Paseo Delicias', 'Rancho Santa Fe, CA 92067'],
    },
    phone: '+18587711871',
    display_phone: '(858) 771-1871',
    distance: 13367.614114504699,
  },
  {
    id: '3E5k18dmXHsXckFaVuz__w',
    alias: 'sinbad-ultra-lounge-san-marcos-9',
    name: 'Sinbad Ultra Lounge',
    image_url:
      'https://s3-media4.fl.yelpcdn.com/bphoto/WruTYRlGuYhqDCjnPt4TIA/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/sinbad-ultra-lounge-san-marcos-9?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
    review_count: 30,
    categories: [
      {
        alias: 'mediterranean',
        title: 'Mediterranean',
      },
      {
        alias: 'lounges',
        title: 'Lounges',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 33.151322,
      longitude: -117.194367,
    },
    transactions: ['pickup', 'delivery'],
    price: '$',
    location: {
      address1: '1551 W Mission Rd',
      address2: 'Ste B-C',
      address3: '',
      city: 'San Marcos',
      zip_code: '92069',
      country: 'US',
      state: 'CA',
      display_address: ['1551 W Mission Rd', 'Ste B-C', 'San Marcos, CA 92069'],
    },
    phone: '+17602903221',
    display_phone: '(760) 290-3221',
    distance: 2030.864738059355,
  },
  {
    id: 'dP9fuoCZOWYBLWK2o_TLHg',
    alias: 'amalfi-marina-bar-san-marcos-2',
    name: 'Amalfi Marina Bar',
    image_url:
      'https://s3-media1.fl.yelpcdn.com/bphoto/hIf1rLjOY7tSuc9Ko7piQA/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/amalfi-marina-bar-san-marcos-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
    review_count: 62,
    categories: [
      {
        alias: 'bars',
        title: 'Bars',
      },
      {
        alias: 'tradamerican',
        title: 'American (Traditional)',
      },
    ],
    rating: 4,
    coordinates: {
      latitude: 33.12391258304946,
      longitude: -117.20782826849721,
    },
    transactions: [],
    price: '$$',
    location: {
      address1: '1035 La Bonita Dr',
      address2: 'Ste B',
      address3: null,
      city: 'San Marcos',
      zip_code: '92078',
      country: 'US',
      state: 'CA',
      display_address: ['1035 La Bonita Dr', 'Ste B', 'San Marcos, CA 92078'],
    },
    phone: '+17606533230',
    display_phone: '(760) 653-3230',
    distance: 3234.351446302782,
  },
  {
    id: '36wSMQzjJie27rcaVCB4kQ',
    alias: 'westbrew-vista',
    name: 'WestBrew',
    image_url:
      'https://s3-media1.fl.yelpcdn.com/bphoto/vfsYlwcOJrkRbEi3z4XlQQ/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/westbrew-vista?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
    review_count: 66,
    categories: [
      {
        alias: 'breweries',
        title: 'Breweries',
      },
      {
        alias: 'pubs',
        title: 'Pubs',
      },
    ],
    rating: 5,
    coordinates: {
      latitude: 33.15339833,
      longitude: -117.22684833,
    },
    transactions: ['pickup', 'delivery'],
    location: {
      address1: '1061 La Mirada Ct',
      address2: null,
      address3: '',
      city: 'Vista',
      zip_code: '92081',
      country: 'US',
      state: 'CA',
      display_address: ['1061 La Mirada Ct', 'Vista, CA 92081'],
    },
    phone: '+18584124364',
    display_phone: '(858) 412-4364',
    distance: 4831.854289517074,
  },
  {
    id: 'bEVu2H35rs8VhFZ0pY6PaA',
    alias: 'san-elijo-vine-and-tap-san-marcos',
    name: 'San Elijo Vine & Tap',
    image_url:
      'https://s3-media3.fl.yelpcdn.com/bphoto/Bs2rbg1r6eM-IwA3t3cIaA/o.jpg',
    is_closed: false,
    url: 'https://www.yelp.com/biz/san-elijo-vine-and-tap-san-marcos?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
    review_count: 339,
    categories: [
      {
        alias: 'wine_bars',
        title: 'Wine Bars',
      },
      {
        alias: 'tradamerican',
        title: 'American (Traditional)',
      },
      {
        alias: 'salad',
        title: 'Salad',
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 33.0976105,
      longitude: -117.1997986,
    },
    transactions: ['delivery'],
    price: '$$',
    location: {
      address1: '1231 Elfin Forest Rd W',
      address2: 'Ste 110',
      address3: '',
      city: 'San Marcos',
      zip_code: '92078',
      country: 'US',
      state: 'CA',
      display_address: [
        '1231 Elfin Forest Rd W',
        'Ste 110',
        'San Marcos, CA 92078',
      ],
    },
    phone: '+17607989804',
    display_phone: '(760) 798-9804',
    distance: 5021.865339062254,
  },
];
